// <auto-generated />
using Healt_Food.Server.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Healt_Food.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230603134103_testSeed1.4")]
    partial class testSeed14
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Healt_Food.Shared.Entites.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<double>("Fat")
                        .HasColumnType("float");

                    b.Property<bool>("Favorite")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 12.0,
                            Carbohydrates = 1234.0,
                            DayOfWeek = 1,
                            Fat = 15.0,
                            Favorite = false,
                            Name = "Foo",
                            Protein = 15.0
                        },
                        new
                        {
                            Id = 2,
                            Calories = 123.0,
                            Carbohydrates = 124.0,
                            DayOfWeek = 2,
                            Fat = 1.0,
                            Favorite = true,
                            Name = "Bar",
                            Protein = 515.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
